version: '3.9'

services:
  update:
    image: sshaccess
    network_mode: host
    entrypoint: ["sh", "-c"]
    command: ["ssh -o BatchMode=yes -o StrictHostKeyChecking=no -q root@192.168.123.123 'exit' && echo 'SSH access verified' || echo 'SSH access failed'"]
